invcog:
  k: 5
  dataname: junyi
  test_num: 6
  epoch: 100
  pretrain_epoch: 200
  gamma: 0.1
  omega: 0.1
  batch_size: 64
  lr: 0.0005
  warmup_steps: 100
  training_steps: 100000
  mean_type: 'x0'
  noise_schedule: 'linear-var'
  noise_scale: 0.0001
  noise_min: 0.0005
  noise_max: 0.005
  p_steps: 2
  cross_embed_size: 512
  cross_heads: 4
  cross_dropout_rate: 0.1
  ce_embed_size: 512
  ce_heads: 4
  ce_dropout: 0.1
  se_dropout: 0.1
  se_heads: 4
  se_embed_size: 512
  inv_embed_size: 512
  backbone_heads: 4
  backbone_dropout: 0.1
  patience: 10
  pretrain: False
  train: False
  wodiff: False
  wosemantic: False
  seed: 0
  semantic_extractor: bge-m3
  sparsity: 0
